### ISSUE TITLE
database creation

### ISSUE THREAD

**Issue by aftechro** [aiman1717a/nova-menu-builder#1]
i cant make it work...for some reason, no database created.
what`s the database structure please?

thank you!

**Comment by aiman1717a** [comment]
Try this command to publish the migration file and the config file
`php artisan vendor:publish --provider="Aiman\MenuBuilder\ToolServiceProvider"`

After that run the migration command
`php artisan migrate`

then the seeder
`php artisan db:seed`

follow the rest of the docs
